### ISSUE TITLE
[BUG] Exception running list-engines immediately after install of 8.1.3.dev53

### ISSUE THREAD

**Issue by ml019** [hamlet-io/executor-python#175]
## Current Behaviour
Exception thrown
```
hamlet engine list-engines
Traceback (most recent call last):
  File "/home/ml019/.pyenv/versions/3.8.0/bin/hamlet", line 8, in <module>
    sys.exit(command.root())
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/display.py", line 47, in wrapper
    result = func(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/exceptions.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/engine/__init__.py", line 58, in list_engines
    for engine in engine_store.engines:
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/__init__.py", line 45, in engines
    self._load_engines()
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/__init__.py", line 89, in _load_engines
    for engine in loader.load():
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/engine_loader.py", line 109, in load
    digest=engine_state['install']['digest'],
KeyError: 'install'
```

## Expected Behaviour
List of installed engines displayed

## Possible Solution
With the recent changes to cacheing, I'm thinking its expecting the default global engine to be installed already?

## Steps to Reproduce

1. `pip install --pre hamlet-cli`
2. `hamlet engine list-engines`
3.
4.

## Your Environment
```
> hamlet --version
hamlet, version 8.1.3.dev52
```

**Comment by ml019** [comment]
Just installed 
```
hamlet --version
hamlet, version 8.1.3.dev53
```

Getting the same result 
```
Traceback (most recent call last):
  File "/home/ml019/.pyenv/versions/3.8.0/bin/hamlet", line 8, in <module>
    sys.exit(command.root())
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 99, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 194, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 43, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 142, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 70, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/exceptions.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/__init__.py", line 57, in root
    setup_global_engine()
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/engine_setup.py", line 13, in setup_global_engine
    global_engine = engine_store.get_engine(ENGINE_GLOBAL_NAME)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/__init__.py", line 97, in get_engine
    self._load_engines()
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/__init__.py", line 89, in _load_engines
    for engine in loader.load():
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/engine_loader.py", line 109, in load
    digest=engine_state['install']['digest'],
KeyError: 'install'
```

**Comment by roleyfoley** [comment]
@ml019 can you run `hamlet engine clean-engines` and then try and list them again. 

There is supposed to be an exception that your engine state version is out of date. Looks like that hasn't worked on the list command

Do you get an error if you run one of the other hamlet commands like `hamlet entrance list-entrances`

**Comment by ml019** [comment]
Exception when I try and clean engines.

```
hamlet engine clean-engines
Traceback (most recent call last):
  File "/home/ml019/.pyenv/versions/3.8.0/bin/hamlet", line 8, in <module>
    sys.exit(command.root())
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 99, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 194, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 43, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 142, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 70, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/exceptions.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/__init__.py", line 57, in root
    setup_global_engine()
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/engine_setup.py", line 13, in setup_global_engine
    global_engine = engine_store.get_engine(ENGINE_GLOBAL_NAME)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/__init__.py", line 97, in get_engine
    self._load_engines()
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/__init__.py", line 89, in _load_engines
    for engine in loader.load():
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/engine_loader.py", line 109, in load
    digest=engine_state['install']['digest'],
KeyError: 'install'
```

Same goes for list-entrances
```
hamlet entrance list-entrances
Traceback (most recent call last):
  File "/home/ml019/.pyenv/versions/3.8.0/bin/hamlet", line 8, in <module>
    sys.exit(command.root())
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 99, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 194, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 43, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 142, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/decorators.py", line 70, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/exceptions.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/__init__.py", line 57, in root
    setup_global_engine()
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/command/common/engine_setup.py", line 13, in setup_global_engine
    global_engine = engine_store.get_engine(ENGINE_GLOBAL_NAME)
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/__init__.py", line 97, in get_engine
    self._load_engines()
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/__init__.py", line 89, in _load_engines
    for engine in loader.load():
  File "/home/ml019/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hamlet/backend/engine/engine_loader.py", line 109, in load
    digest=engine_state['install']['digest'],
KeyError: 'install'
```

**Comment by ml019** [comment]
I uninstalled hamlet-cli and manually deleted the `.hamlet/engines` directory.

Then reinstalled. Behaving much better

```
 hamlet engine list-engines
| Name     | Description                               | Installed   | Global   | Update Available   |
|----------|-------------------------------------------|-------------|----------|--------------------|
| unicycle | Latest build of the official engine parts | False       | False    | None               |
| tram     | Nightly build of the official engine      | False       | False    | None               |
```

**Comment by ml019** [comment]
Engine installed on first command
```
 hamlet entrance list-entrances
[*] No default engine found installing default engine - tram
[*] Setting the global engine to the default engine - tram
╒════╤════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╕
│    │ Type           │ Description                                                                                                                    │
╞════╪════════════════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│  0 │ blueprint      │ Provides a detailed representation of everything in a given segment, this includes its parent, environment, product and tenant │
├────┼────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  1 │ buildblueprint │ Provides a given deployment units occurrences and their suboccurrences                                                         │
├────┼────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  2 │ deployment     │ Generates the required documents to deploy a given deployment unit / deployment group combination                              │
├────┼────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  3 │ deploymenttest │ Generates the required documents to deploy a given deployment unit / deployment group combination                              │
├────┼────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  4 │ info           │ Provides details on the hamlet engine and the avaiable entrances                                                               │
├────┼────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  5 │ loader         │ Generates a set of loader contracts which can be used to setup hamlet                                                          │
├────┼────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  6 │ occurrences    │ Provides the state of all occurrences within a district                                                                        │
├────┼────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  7 │ schema         │ Povides JSON schema representations of input configuration                                                                     │
├────┼────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  8 │ schemaset      │ Generates Schema Contracts that are used to generate all JSONSchema files by their data type.                                  │
├────┼────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  9 │ unitlist       │ Provides details on all deployment unit | deployment group combinations                                                        │
├────┼────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 10 │ validate       │ Performs validation of the current Blueprint Object                                                                            │
╘════╧════════════════╧════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╛
```

**Comment by roleyfoley** [comment]
Issue was with the loading of installed engines. installed engine loading acts as a fall back if for some reason we can't load engines from the library. 

Added a check which will skip invalid engines and only show compatible ones
